## Completed
* Data assembling

## To do
* SQL database
* Data Cleaning

In [1]:
import pandas as pd

In [2]:
import sqlite3
from sqlalchemy import create_engine
from sqlalchemy import inspect

In [3]:
sqlite3.connect('mlb_2015_2019.db')

In [4]:
engine = create_engine('sqlite:///mlb_2015_2019.db')

In [5]:
df = pd.read_csv('data/scherzer.csv')
df.to_sql('scherzer',con=engine)

/opt/anaconda3/envs/metis/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3441: DtypeWarning: Columns (19,21,50) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [6]:
df

,Unnamed: 0,px,pz,start_speed,end_speed,spin_rate,spin_dir,break_angle,break_length,break_y,...,start_time,umpire_1B,umpire_2B,umpire_3B,umpire_HP,venue_name,weather,wind,delay,year
0,0,-1.598,1.869,90.6,82.8,2704.451,235.379,43.7,6.2,23.7,...,16:09,Tim Timmons,Chris Segal,Todd Tichenor,Tim Welke,Nationals Park,"76 degrees, sunny","14 mph, Out to CF",0.0,2015
1,1,-0.909,2.487,93.5,85.0,2536.460,221.465,41.6,4.5,23.7,...,16:09,Tim Timmons,Chris Segal,Todd Tichenor,Tim Welke,Nationals Park,"76 degrees, sunny","14 mph, Out to CF",0.0,2015
2,2,-1.585,2.934,94.9,86.6,2546.016,220.551,44.2,4.2,23.7,...,16:09,Tim Timmons,Chris Segal,Todd Tichenor,Tim Welke,Nationals Park,"76 degrees, sunny","14 mph, Out to CF",0.0,2015
3,3,0.364,0.245,86.6,79.9,1628.200,245.895,21.3,7.5,23.8,...,16:09,Tim Timmons,Chris Segal,Todd Tichenor,Tim Welke,Nationals Park,"76 degrees, sunny","14 mph, Out to CF",0.0,2015
4,4,-1.927,4.250,94.0,85.7,2040.141,229.179,34.2,5.0,23.7,...,16:09,Tim Timmons,Chris Segal,Todd Tichenor,Tim Welke,Nationals Park,"76 degrees, sunny","14 mph, Out to CF",0.0,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16307,16307,-0.530,2.740,79.1,73.0,2818.000,NaN,12.0,9.6,24.0,...,19:05,NaN,NaN,NaN,NaN,Nationals Park,NaN,NaN,NaN,2019
16308,16308,1.390,0.800,84.8,78.5,2295.000,NaN,7.2,8.4,24.0,...,19:05,NaN,NaN,NaN,NaN,Nationals Park,NaN,NaN,NaN,2019
16309,16309,-0.120,2.180,97.4,89.3,2465.000,NaN,38.4,3.6,24.0,...,19:05,NaN,NaN,NaN,NaN,Nationals Park,NaN,NaN,NaN,2019
16310,16310,0.650,1.460,84.4,77.9,1494.000,NaN,24.0,9.6,24.0,...,19:05,NaN,NaN,NaN,NaN,Nationals Park,NaN,NaN,NaN,2019
16311,16311,0.620,2.780,92.7,85.2,2299.000,NaN,33.6,4.8,24.0,...,19:05,NaN,NaN,NaN,NaN,Nationals Park,NaN,NaN,NaN,2019

In [17]:
df['year'] = df['g_id'].astype('string').map(lambda x : x[:4]).astype('int')

In [18]:
df['year']

0        2015
1        2015
2        2015
3        2015
4        2015
         ...
16307    2019
16308    2019
16309    2019
16310    2019
16311    2019
Name: year, Length: 16312, dtype: int64

In [19]:
df.groupby(['year','pitch_type']).count()

                   px    pz  start_speed  end_speed  spin_rate  spin_dir  \
year pitch_type
2015 CH           440   440          440        440        440       440
     CU           271   271          271        271        271       271
     FC            55    55           55         55         55        55
     FF          1988  1988         1988       1988       1988      1988
     SL           598   598          598        598        598       598
2016 CH           427   427          427        427        427       427
     CU           287   287          287        287        287       287
     FC            61    61           61         61         61        61
     FF          1968  1968         1968       1968       1968      1968
     SL           811   811          811        811        811       811
     UN             1     1            1          1          1         1
2017 CH           441   441          441        441        441       441
     CU           255   255          255        255        255       255
     FC           237   237          237        237        237       237
     FF          1415  1415         1415       1415       1415      1415
     FT            89    89           89         89         89        89
     SL           656   656          656        656        656       656
2018 CH           548   548          548        548        548       548
     CU           277   277          277        277        277       277
     FC           335   335          335        335        335       335
     FF          1746  1746         1746       1746       1746      1746
     SL           574   574          574        574        574       574
2019 CH           401   401          401        401        401       401
     CU           240   240          240        240        240       240
     FC           214   214          214        214        214       214
     FF          1341  1341         1341       1341       1341      1341
     SL           573   573          573        573        573       573

                 break_angle  break_length  break_y    ax  ...  home_team  \
year pitch_type                                            ...
2015 CH                  440           440      440   440  ...        440
     CU                  271           271      271   271  ...        271
     FC                   55            55       55    55  ...         55
     FF                 1988          1988     1988  1988  ...       1988
     SL                  598           598      598   598  ...        598
2016 CH                  427           427      427   427  ...        427
     CU                  287           287      287   287  ...        287
     FC                   61            61       61    61  ...         61
     FF                 1968          1968     1968  1968  ...       1968
     SL                  811           811      811   811  ...        811
     UN                    1             1        1     1  ...          1
2017 CH                  441           441      441   441  ...        441
     CU                  255           255      255   255  ...        255
     FC                  237           237      237   237  ...        237
     FF                 1415          1415     1415  1415  ...       1415
     FT                   89            89       89    89  ...         89
     SL                  656           656      656   656  ...        656
2018 CH                  548           548      548   548  ...        548
     CU                  277           277      277   277  ...        277
     FC                  335           335      335   335  ...        335
     FF                 1746          1746     1746  1746  ...       1746
     SL                  574           574      574   574  ...        574
2019 CH                  401           401      401   401  ...        401
     CU                  240           240      240   240  ...        240
     FC                  214           214      214   214  ...        214
     FF                 1341          1341     1341  1341  ...       1341
     SL                  573           573      573   573  ...        573

                 start_time  umpire_1B  umpire_2B  umpire_3B  umpire_HP  \
year pitch_type
2015 CH                 440        440        440        440        440
     CU                 271        271        271        271        271
     FC                  55         55         55         55         55
     FF                1988       1988       1988       1988       1988
     SL                 598        598        598        598        598
2016 CH                 427        427        427        427        427
     CU                 287        287        287        287        287
     FC                  61         61         61         61         61
     FF                1968       1968       1968       1968       1968
     SL                 811        811        811        811        811
     UN                   1          1          1          1          1
2017 CH                 441        441        441        441        441
     CU                 255        255        255        255        255
     FC                 237        237        237        237        237
     FF                1415       1415       1415       1415       1415
     FT                  89         89         89         89         89
     SL                 656        656        656        656        656
2018 CH                 548        548        548        548        548
     CU                 277        277        277        277        277
     FC                 335        335        335        335        335
     FF                1746       1746       1746       1746       1746
     SL                 574        574        574        574        574
2019 CH                   0          0          0          0          0
     CU                   0          0          0          0          0
     FC                   0          0          0          0          0
     FF                   0          0          0          0          0
     SL                   0          0          0          0          0

                 venue_name  weather  wind  delay
year pitch_type
2015 CH                 440      440   440    440
     CU                 271      271   271    271
     FC                  55       55    55     55
     FF                1988     1988  1988   1988
     SL                 598      598   598    598
2016 CH                 427      427   427    427
     CU                 287      287   287    287
     FC                  61       61    61     61
     FF                1968     1968  1968   1968
     SL                 811      811   811    811
     UN                   1        1     1      1
2017 CH                 441      441   441    441
     CU                 255      255   255    255
     FC                 237      237   237    237
     FF                1415     1415  1415   1415
     FT                  89       89    89     89
     SL                 656      656   656    656
2018 CH                 548      548   548    548
     CU                 277      277   277    277
     FC                 335      335   335    335
     FF                1746     1746  1746   1746
     SL                 574      574   574    574
2019 CH                 401        0     0      0
     CU                 240        0     0      0
     FC                 214        0     0      0
     FF                1341        0     0      0
     SL                 573        0     0      0

[27 rows x 65 columns]

In [21]:
df.groupby(['pitch_type']).count()

,px,pz,start_speed,end_speed,spin_rate,spin_dir,break_angle,break_length,break_y,ax,...,start_time,umpire_1B,umpire_2B,umpire_3B,umpire_HP,venue_name,weather,wind,delay,year
pitch_type,,,,,,,,,,,,,,,,,,,,,
CH,2257,2257,2257,2257,2257,2257,2257,2257,2257,2257,...,1856,1856,1856,1856,1856,2257,1856,1856,1856,2257
CU,1330,1330,1330,1330,1330,1330,1330,1330,1330,1330,...,1090,1090,1090,1090,1090,1330,1090,1090,1090,1330
FC,902,902,902,902,902,902,902,902,902,902,...,688,688,688,688,688,902,688,688,688,902
FF,8458,8458,8458,8458,8458,8458,8458,8458,8458,8458,...,7117,7117,7117,7117,7117,8458,7117,7117,7117,8458
FT,89,89,89,89,89,89,89,89,89,89,...,89,89,89,89,89,89,89,89,89,89
SL,3212,3212,3212,3212,3212,3212,3212,3212,3212,3212,...,2639,2639,2639,2639,2639,3212,2639,2639,2639,3212
UN,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1